/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ulises.posverse.rest.api;

import com.ulises.posverse.rest.api.dto.category.create.requests.CategoryCreationRequestDTO;
import com.ulises.posverse.rest.api.dto.category.create.responses.CategoryCreationResponseDTO;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen",
        date = "2025-07-18T14:39:42.224865400+02:00[Europe/Madrid]", comments = "Generator version: 7.4.0")
@Validated
@Tag(name = "categories", description = "the categories API")
public interface CategoriesApi {

    /**
     * POST /categories : Creates a category
     *
     * @param categoryCreationRequestDTO Category creation request (required)
     * @return Created (status code 201)
     */
    @Operation(
        operationId = "createCategory",
        summary = "Creates a category",
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CategoryCreationResponseDTO.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/categories",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<CategoryCreationResponseDTO> createCategory(
        @Parameter(name = "CategoryCreationRequestDTO", description = "Category creation request", required = true)
        @Valid @RequestBody final CategoryCreationRequestDTO categoryCreationRequestDTO
    );

}
