/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ulises.posverse.rest.api;

import com.ulises.posverse.rest.api.dto.product.create.requests.ProductCreationRequestDTO;
import com.ulises.posverse.rest.api.dto.product.retrieval.filters.PagedProductsRetrievalFilters;
import com.ulises.posverse.rest.api.dto.product.retrieval.responses.PagedProductsRetrievalResponseDTO;
import com.ulises.posverse.rest.api.dto.product.create.responses.ProductCreationResponseDTO;
import com.ulises.posverse.rest.api.dto.product.retrieval.responses.ProductRetrievalResponseDTO;
import com.ulises.posverse.rest.api.dto.product.retrieval.filters.PagedProductsRetrievalPagingParam;
import com.ulises.posverse.rest.api.dto.product.update.requests.ProductUpdateRequestDTO;
import com.ulises.posverse.rest.api.dto.product.update.responses.ProductUpdateResponseDTO;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen",
        date = "2025-07-18T10:50:11.431661200+02:00[Europe/Madrid]", comments = "Generator version: 7.4.0")
@Validated
@Tag(name = "products", description = "the products API")
public interface ProductsApi {

    /**
     * POST /products : Creates a product
     *
     * @param productCreationRequestDTO Product creation request (required)
     * @return Created (status code 201)
     */
    @Operation(
            operationId = "createProduct",
            summary = "Creates a product",
            responses = {
                    @ApiResponse(responseCode = "201", description = "Created", content = {
                            @Content(mediaType = "application/json",
                                    schema = @Schema(implementation = ProductCreationResponseDTO.class))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/products",
            produces = { "application/json" },
            consumes = { "application/json" }
    )

    ResponseEntity<ProductCreationResponseDTO> createProduct(
            @Parameter(name = "ProductCreationRequestDTO", description = "Product creation request",
                    required = true) @Valid @RequestBody final ProductCreationRequestDTO productCreationRequestDTO
    );

    /**
     * GET /products/{id} : Retrieves a product by id
     *
     * @param productId Product ID (required)
     * @return OK (status code 200)
     */
    @Operation(
            operationId = "getProductById",
            summary = "Retrieves a product by id",
            responses = {
                    @ApiResponse(responseCode = "200", description = "OK", content = {
                            @Content(mediaType = "application/json",
                                    schema = @Schema(implementation = ProductRetrievalResponseDTO.class))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/products/{productId}",
            produces = { "application/json" }
    )

    ResponseEntity<ProductRetrievalResponseDTO> getProductById(
            @Parameter(name = "productId", description = "Retrieves a product by id",
                    required = true) @PathVariable final Long productId
    );

    /**
     * GET /products : Retrieves a product by id
     *
     * @param pagingParams request params
     * @return OK (status code 200)
     */
    @Operation(
            operationId = "getPagedProductsList",
            summary = "Retrieves paged list of products",
            responses = {
                    @ApiResponse(responseCode = "200", description = "OK", content = {
                            @Content(mediaType = "application/json",
                                    schema = @Schema(implementation = PagedProductsRetrievalResponseDTO.class))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/products",
            produces = { "application/json" }
    )

    ResponseEntity<PagedProductsRetrievalResponseDTO> getPagedProductsList(
            @Parameter(name = "pagingParams", description = "The parameters to perform the paged request")
            @ModelAttribute final PagedProductsRetrievalPagingParam pagingParams,
            @ModelAttribute final PagedProductsRetrievalFilters filters
    );

    /**
     * DELETE /products{id} : Deletes a product by id
     *
     * @param productId productId
     * @return OK (status code 204)
     */
    @Operation(
            operationId = "deleteProductById",
            summary = "Deletes a product by id",
            responses = {
                    @ApiResponse(responseCode = "204", description = "NO_CONTENT", content = {
                            @Content(mediaType = "application/json")
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.DELETE,
            value = "/products/{productId}"
    )
    ResponseEntity<Void> deleteProductById(
            @Parameter(name = "productId", description = "Product id",
                    required = true) @PathVariable final Long productId
    );

    /**
     * PUT /products : Creates a product
     *
     * @param productUpdateRequestDTO Product update request (required)
     * @return OK (status code 2001)
     */
    @Operation(
            operationId = "updateProduct",
            summary = "Updates a product",
            responses = {
                    @ApiResponse(responseCode = "200", description = "OK", content = {
                            @Content(mediaType = "application/json",
                                    schema = @Schema(implementation = ProductUpdateResponseDTO.class))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.PUT,
            value = "/products/{productId}",
            produces = { "application/json" },
            consumes = { "application/json" }
    )

    ResponseEntity<ProductUpdateResponseDTO> updateProduct(
            @Parameter(name = "ProductCreationRequestDTO", description = "Product update request",
                    required = true) @Valid @RequestBody final ProductUpdateRequestDTO productUpdateRequestDTO,
            @Parameter(name = "productId", description = "Product ID",
                    required = true) @PathVariable final Long productId
    );

}
