openapi: "3.0.1"
info:
  title: API de ejemplo
  version: 1.0.0
paths:
  /products:
    post:
      summary: Creates a product
      operationId: createProduct
      requestBody:
        required: true
        description: "Product creation request"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreationRequestDTO'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCreationResponseDTO'
components:
  schemas:
    ProductBase:
      type: object
      required:
        - name
      properties:
        name: { type: string, example: "Coke" }
        salePrice: { type: number, format: double, example: 2.50 }
        purchasePrice: { type: number, format: double, example: 0.70 }
        description: { type: string, example: "Refreshing drink" }
        isCompositeProduct: { type: boolean, example: true }
        isAvailableForSale: { type: boolean, example: true }
        mustTrackStock: { type: boolean }
        stockAmount: { type: number, format: double, example: 102 }
        lowStockWarning: { type: number, format: double, example: 24 }

    ProductCreationRequestDTO:
      allOf:
        - $ref: '#/components/schemas/ProductBase'

    ProductCreationResponseDTO:
      allOf:
        - $ref: '#/components/schemas/ProductBase'
        - type: object
          required:
            - id
          properties:
            id: { type: integer, format: int64, example: 1}
